spring:
  datasource:
    url: jdbc:sqlserver://mysql02.database.windows.net:1433;database=root;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: shobhit
    password: root@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8082


